defaultNamespace: nginx-app
helm:
  releaseName: nginx-deployment
  chart: ./nginx-chart
  values:
    replicaCount: 1
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      host: nginx-app.demo.home.arpa


